language: node_js
node_js:
- 8
script: npm run lint && npm test && npm i && npm run build
deploy:
  provider: npm
  email: ackeedevelopment@gmail.com
  skip_cleanup: true
  api_key:
    secure: xrOwV8IPrmyT1n1cKAI/OM7p5oPW92OBqj3ayoRF/XXfg4RlSVDOb6i8h4qF66OkBhUJB1uLym8RfT//EmU4/gDjD3pODISRNGpTj8AO7rSXMyCfITem0ETPERBDUJF6MicMdIj466Vdkhum31Q9PcdnntbRyxssucnp9cnoxnl3b082ERjFpUHdEjsHwtH1CnD/XXLBcn2MNAc9/aPIR3TP79IiBZnClXLQRlFMZXl5mMqlHRrf7XMbJBINEtGsjtbLBMeBio9ksSUXymgATXmM4rxZ04DPNtUx5dHM6ENT97T20ne6LuTO/qoDe1FyuqDQNmcOgiBhytrBsNjz3JaK463KWysDQfMCHwC8UVMDafXktESI8n18YL2xKmlg7PL2O9wdShRrurv6+r51QtM2TqepugBs+kuUJ1Gk2MAPtTCUutlGbWr/kKc9zQR8vDNyh4tl+TZMmE2tvZj+joIPm83/LnpQVN6Cpf48m1nDYMBWoWBB3Mwd+z5sx+6eoQA9Tpr9+REcspuiOHjQkq3JXLIFg/XPKENQ8CKf/uMbkGqDd1N2XF5ODfll8OrZ05xnUcJkA969jpbabSOgbeqLlLWgIDWiMsGdyYmYMCVlE3KVnTc0mevdzMCXNRoNtu6KsJwN1XBTnf3OJ6pWhTt/33Oc5BuYNq8q70i6cl0=
  on:
    tags: true
    repo: AckeeCZ/mateus
